apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  config.conf: |
    server {
        listen 80;
        server_name _;

        location / {
            proxy_pass http://chatapp-backend:8000;
        }
    }
