apiVersion: v1
kind: Pod
metadata:
  name: chatapp-db
  labels:
    app: chatapp-db
spec:
  containers:
    - name: chatapp-db
      image: mysql
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: configmap-db
        - secretRef:
            name: db-secret
      resources:
        requests:
          cpu: "250m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
